"""add composite_signal table

Revision ID: b5fa91ddaaf1
Revises: f21eb06274bd
Create Date: 2026-06-12 14:35:43.038708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b5fa91ddaaf1'
down_revision: Union[str, None] = 'f21eb06274bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('accuracy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composite_signal_created_at'), 'composite_signal', ['created_at'], unique=False)
    op.create_index(op.f('ix_composite_signal_symbol'), 'composite_signal', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composite_signal_symbol'), table_name='composite_signal')
    op.drop_index(op.f('ix_composite_signal_created_at'), table_name='composite_signal')
    op.drop_table('composite_signal')
    # ### end Alembic commands ###
