"""add ai_usage_log table

Revision ID: c442627bb43d
Revises: c3a7e1f2b4d5
Create Date: 2026-05-25 15:50:23.979769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c442627bb43d'
down_revision: Union[str, None] = 'c3a7e1f2b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('caller', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_log_time', 'ai_usage_log', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_ai_usage_log_time', table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
