"""init tables

Revision ID: cb39399457bb
Revises:
Create Date: 2026-03-26 16:45:52.318441

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb39399457bb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_report",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("model_used", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("sentiment_score", sa.Integer(), nullable=False),
        sa.Column("trend", sa.String(length=16), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("data_sources", sa.JSON(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_analysis_scope_time",
        "analysis_report",
        ["scope", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "defi_metric",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("protocol", sa.String(length=64), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("tvl", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("tvl_change_24h", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol", "chain", "timestamp", name="uq_defi_metric"),
    )
    op.create_table(
        "dex_volume",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("dex", sa.String(length=64), nullable=False),
        sa.Column("pair", sa.String(length=64), nullable=False),
        sa.Column("volume_24h", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("liquidity_usd", sa.Numeric(precision=24, scale=2), nullable=False),
        sa.Column("txns_24h", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "dex", "pair", "timestamp", name="uq_dex_volume"),
    )
    op.create_table(
        "news_article",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("sentiment", sa.String(length=16), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_news_url"),
    )
    op.create_index(
        "ix_news_published",
        "news_article",
        [sa.text("published_at DESC")],
        unique=False,
    )
    op.create_table(
        "ohlcv_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "exchange", "timeframe", "timestamp", name="uq_ohlcv"
        ),
    )
    op.create_index(
        "ix_ohlcv_lookup",
        "ohlcv_data",
        ["symbol", "exchange", "timeframe", sa.text("timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ohlcv_lookup", table_name="ohlcv_data")
    op.drop_table("ohlcv_data")
    op.drop_index("ix_news_published", table_name="news_article")
    op.drop_table("news_article")
    op.drop_table("dex_volume")
    op.drop_table("defi_metric")
    op.drop_index("ix_analysis_scope_time", table_name="analysis_report")
    op.drop_table("analysis_report")
    # ### end Alembic commands ###
